### ISSUE TITLE
FAWE not working.

### ISSUE THREAD

**Issue by BatchWhoAmI** [InsightsPlugin/InsightsWorldEditExtension#6]
Doesnt work with FastAsyncWorldEdit, fix asap.

**Comment by FrankHeijden** [comment]
Seems there's a bug with FAWE as well, which prohibits the functionality from being added on FAWE: https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1046, so we will need to wait on that first.

**Comment by FrankHeijden** [comment]
Hey, just released v3; to use FAWE with this extension you may need to add the following entry to your FAWE's config.yml:
```yaml
allowed-plugins:
- "dev.frankheijden.insights.extensions.worldedit.fawe.FaweWorldEditExtent"
```
