### ISSUE TITLE
Limit bypass

### ISSUE THREAD

**Issue by almic** [InsightsPlugin/InsightsWorldEditExtension#9]
Using `//stack` in FAWE will bypass all limits.

## Reproducing
1. Set a 64 block limit for redstone pistons
2. Place 64 pistons in a chunk
3. Select them using WE
4. `//stack` until server crumbles

Also, please make some way to report things like this more privately. I love this plugin and I've only discovered it today, but having to share a bypass like this publicly in order to report it could be deadly to servers in the future.

**Comment by FrankHeijden** [comment]
Thanks, fixed in v3.2.0. You may also join the discord for future issues you encounter, and ask for a DM if the matter is sensitive :)
